pipelines:
 - name: test_api
   steps:
     - name: test_api_1
       type: Bash
       execution:
         onExecute:
           - curl -XPOST -s --fail -H "Content-Type: application/json" -H "Authorization: Bearer ${token}" "https://testrahul18102101.jfrogdev.org/ui/api/v1/pipe/api/v1/pipelineSteps/${stepId}/trigger" -d "{}"
           
