pipelines:
 - name: test_api
   steps:
     - name: test_api_1
       type: Bash
       execution:
         onExecute:
           - echo $builder_api_token
           - |
            curl -XPOST -s -H "Content-Type: application/json" -H "Authorization: Bearer $builder_api_token" "https://testrahul18102101.jfrogdev.org/pipelines/api/v1/pipelineSteps/1/trigger" -d "{}"
           
